### ISSUE TITLE
build project

### ISSUE THREAD

**Issue by Gambler19** [egecetin/VideoStabilization#1] opened 2024-01-22 15:04 UTC
could u give instruction how to build this project?
i have a problem when i build this project: atal error: opencv2/cudaarithm.hpp: No such file or directory
    9 | #include <opencv2/cudaarithm.hpp>

**Comment by egecetin** [comment] 2024-01-22 16:14
@Gambler19 This project assumes you have already installed OpenCV in your system. So, this error can be caused by one of the following reasons,

- First of all check the `cudaarithm.hpp` file location. It may be moved to some different folder. My suggestion is `locate` command if you are in a linux environment. Use `locate cudaarithm.hpp` and check the result.
- If you can't find the header file (this means previous command returns empty response): Make sure OpenCV compiled with CUDA backend. Check your CUDA and OpenCV installation. If you install OpenCV from pre-built binaries they are not supporting CUDA backend, so you must compile OpenCV in your computer with CUDA backend. First install CUDA in your computer than make sure during CMake configure of OpenCV, you enabled CUDA backend with `-DWITH_CUDA=ON`. You should see a line in your terminal like `"  NVIDIA CUDA: YES (ver <version string>, <cuda features>)`. If you don't know how to compile it CUDA backend I suggest checking some online tutorials because of sometimes OpenCV can be a problematic depending on your module selections (especially with `contrib`).
- If you can find the header file and if you are sure you compiled your OpenCV with CUDA backend, check your installation folder. This line, https://github.com/egecetin/VideoStabilization/blob/4918a9d901d6f53898908680dd58deebadb76bf7/CMakeLists.txt#L6 tries to find your OpenCV installation but if somehow CMake can't find your OpenCV config in your system you should update your include directories. For example, your installation might install your header files in `/some/dir/opencvX/`. Make sure `/some/dir/opencvX/` is in your system search path.

I can try to help you if you have more questions!

**Comment by Gambler19** [comment] 2024-01-23 06:08
Thaks to try help me. I will follow your instructions to build project and after that i report your about my success.

**Comment by Gambler19** [comment] 2024-01-23 13:40
Dear friend, grateful thank u. Project was compiled and worked.
after that  I'm trying to run the application in command line like this: videoStabilization.exe "GoPro Hero 6.MP4" , but video is not stabilized. maybe i do something wrong?

**Comment by egecetin** [comment] 2024-01-24 07:45
@Gambler19 If you mean video is not _completely_ stabilized with 

> but video is not stabilized

Since this is a software based solution for the stabilization, 100% stabilizing of video is not possible. If I remember right by using its default parameters it fails for,

- Videos with fast and big displacements: It uses average to decide the displacement vectors. So for fast displacements the average value can't catch up with the real displacement. It is normal the see still a shaking video but with less shaking when compared with the original video.
- A single big object occupies most of the frame like a face or a huge vehicle (eg. train truck etc.): For detecting displacement vectors it relies on point tracking algorithm. Since point tracking algorithm requires points (you can call it feature points, corner points, good points etc most of them leads similar pixels mostly) when one of the objects occupies lots of pixels most of these tracking points are calculated from the object (because you can't get enough data from background). In this situation even when there is no shaking in the camera side, when this big object moves to a direction there will be a average displacement vector and the algorithm fails to catch up with camera motions. Also it will try to track the object so there will be more shaking more than normal in the stabilized video.

I suggest using some stock videos (from internet/youtube) especially recorded for stabilization demonstration as a first step if you are using your custom video. If the video is _more stabilized_ than the original you can start to adjust variables,

- HISTORY_LIMIT https://github.com/egecetin/VideoStabilization/blob/4918a9d901d6f53898908680dd58deebadb76bf7/src/process.cpp#L117

- SMOOTHING_RADIUS https://github.com/egecetin/VideoStabilization/blob/4918a9d901d6f53898908680dd58deebadb76bf7/src/process.cpp#L122

- Feature detector options (check OpenCV documentation for input variables, maybe even you can replace with another algorithm if you like) https://github.com/egecetin/VideoStabilization/blob/4918a9d901d6f53898908680dd58deebadb76bf7/src/process.cpp#L44

- Tracking options (check OpenCV documentation for input variables, maybe even you can replace with another algorithm if you like) https://github.com/egecetin/VideoStabilization/blob/4918a9d901d6f53898908680dd58deebadb76bf7/src/process.cpp#L52

**Comment by egecetin** [comment] 2024-01-31 08:09
I'm closing the issue for now. You can reopen any time you need it.

**Closed as completed by egecetin** 2024-01-31 08:09 UTC
